# kak-tree-sitter default configuration file.
#
# It is highly recommended for users to copy that file and edit it manually if they need to add support for languages
# not present yet. Also, please consider opening a PR to https://github.com/phaazon/kak-tree-sitter.

# Top-level highlight capture group declarations. If your grammars uses a capture group that is not defined here, you
# have to add it to the list.
highlight.groups = [
  "attribute",
  "comment",
  "comment.block",
  "comment.line",
  "constant",
  "constant.builtin",
  "constant.builtin.boolean",
  "constant.character",
  "constant.character.escape",
  "constant.numeric",
  "constant.numeric.float",
  "constant.numeric.integer",
  "constructor",
  "diff.plus",
  "diff.minus",
  "diff.delta",
  "diff.delta.moved",
  "embedded",
  "error",
  "function",
  "function.builtin",
  "function.macro",
  "function.method",
  "function.special",
  "hint",
  "include",
  "info",
  "keyword",
  "keyword.conditional",
  "keyword.control",
  "keyword.control.conditional",
  "keyword.control.exception",
  "keyword.control.import",
  "keyword.control.repeat",
  "keyword.control.return",
  "keyword.directive",
  "keyword.function",
  "keyword.operator",
  "keyword.special",
  "keyword.storage",
  "keyword.storage.modifier",
  "keyword.storage.modifier.mut",
  "keyword.storage.modifier.ref",
  "keyword.storage.type",
  "label",
  "load",
  "markup.bold",
  "markup.heading",
  "markup.heading.1",
  "markup.heading.2",
  "markup.heading.3",
  "markup.heading.4",
  "markup.heading.5",
  "markup.heading.6",
  "markup.heading.marker",
  "markup.italic",
  "markup.link.label",
  "markup.link.text",
  "markup.link.url",
  "markup.list.checked",
  "markup.list.numbered",
  "markup.list.unchecked",
  "markup.list.unnumbered",
  "markup.quote" ,
  "markup.raw.block",
  "markup.raw.inline",
  "markup.strikethrough",
  "namespace",
  "operator",
  "punctuation",
  "punctuation.bracket",
  "punctuation.delimiter",
  "punctuation.special",
  "special",
  "string",
  "string.escape",
  "string.regexp",
  "string.special",
  "string.special.path",
  "string.special.symbol",
  "string.symbol",
  "tag",
  "tag.error",
  "text",
  "type",
  "type.builtin",
  "type.enum.variant",
  "variable",
  "variable.builtin",
  "variable.other.member",
  "variable.other.member",
  "variable.parameter",
  "warning",
]

# astro
# TODO

# awk
[language.awk.grammar]
url = "https://github.com/Beaglefoot/tree-sitter-awk"
pin = "8eaa762d05cc67c0e2cc53a0a71750b3c16733c2"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "awk.so"]
link_flags = ["-O3"]

[language.awk.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/awk"

# bash
[language.bash.grammar]
url = "https://github.com/tree-sitter/tree-sitter-bash"
pin = "ee2a8f9906b53a785b784ee816c0016c2b6866d2"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "bash.so"]
link_flags = ["-O3"]

[language.bash.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/bash"

# bass
# TODO

# beancount
# TODO

# bibtex
# TODO

# bicep
# TODO

# c
[language.c.grammar]
url = "https://github.com/tree-sitter/tree-sitter-c"
pin = "7175a6dd5fc1cee660dce6fe23f6043d75af424a"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "c.so"]
link_flags = ["-O3"]

[language.c.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/c"

# cabal
# TODO

# cairo
# TODO

# capnp
# TODO

# clojure
# TODO

# cmake
# TODO

# comment
[language.comment.grammar]
url = "https://github.com/stsewd/tree-sitter-comment"
pin = "94c99a66bb5051d8321b5900aee92b76450c50ce"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "comment.so"]
link_flags = ["-O3"]

[language.comment.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/comment"

# common-lisp
# TODO

# cpon
# TODO

# cpp
[language.cpp.grammar]
url = "https://github.com/tree-sitter/tree-sitter-cpp"
pin = "670404d7c689be1c868a46f919ba2a3912f2b7ef"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.cc", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "cpp.so"]
link_flags = ["-O3", "-lstdc++"]

[language.cpp.queries]
url = "https://github.com/phaazon/kak-tree-sitter"
pin = "bf5fbfcd2eee7f26d632607a2046f460aa392a8c"
path = "runtime/queries/cpp"

# crystal
# TODO

# c-sharp
# TODO

# css
# TODO

# cue
# TODO

# d
# TODO

# dart
# TODO

# devicetree
# TODO

# dhall
# TODO

# diff
[language.diff.grammar]
url = "https://github.com/the-mikedavis/tree-sitter-diff"
pin = "fd74c78fa88a20085dbc7bbeaba066f4d1692b63"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "diff.so"]
link_flags = ["-O3"]

[language.diff.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/diff"

# dockerfile
# TODO

# dot
# TODO

# dtd
# TODO

# ecma
# TODO

# edoc
# TODO

# eex
# TODO

# ejs
# TODO

# elixir
# TODO

# elm
# TODO

# elvish
# TODO

# env
# TODO

# erb
# TODO

# erlang
# TODO

# esdl
# TODO

# fish
# TODO

# fortran
# TODO

# gdscript
# TODO

# git-attributes
# TODO

# git-commit
[language.git-commit.grammar]
url = "https://github.com/the-mikedavis/tree-sitter-git-commit"
pin = "db88cffa3952dd2328b741af5d0fc69bdb76704f"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "git-commit.so"]
link_flags = ["-O3"]

[language.git-commit.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/git-commit"

# git-config
# TODO

# git-ignore
# TODO

# git-rebase
# TODO

# gleam
# TODO

# glsl
# TODO

# go
# TODO

# godot-resource
# TODO

# gomod
# TODO

# gotmpl
# TODO

# gowork
# TODO

# graphql
# TODO

# hare
# TODO

# haskell
# TODO

# hcl
# TODO

# heex
# TODO

# hosts
# TODO

# html
[language.html.grammar]
url = "https://github.com/tree-sitter/tree-sitter-html"
pin = "86c253e675e7fdd1c0482efe0706f24bafbc3a7d"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "../scanner.cc", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "html.so"]
link_flags = ["-O3", "-lstdc++"]

[language.html.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/html"

# hurl
# TODO

# iex
# TODO

# ini
# TODO

# java
[language.java.grammar]
url = "https://github.com/tree-sitter/tree-sitter-java"
pin = "c194ee5e6ede5f26cf4799feead4a8f165dcf14d"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "java.so"]
link_flags = ["-O3"]

[language.java.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/java"

# javascript
# TODO

# jsdoc
# TODO

# json
# TODO

# jsonnet
# TODO

# jsx
# TODO

# julia
# TODO

# just
# TODO

# kdl
# TODO

# kotlin
# TODO

# latex
# TODO

# lean
# TODO

# ledger
# TODO

# llvm
# TODO

# llvm-mir
# TODO

# llvm-mir-yaml
# TODO

# lua
# TODO

# make
# TODO

# markdoc
# TODO

# markdown
[language.markdown.grammar]
url = "https://github.com/MDeiml/tree-sitter-markdown"
pin = "231f3163cd27d48f91a4517cfdf72d167a9ef164"
path = "tree-sitter-markdown/src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "markdown.so"]
link_flags = ["-O3"]

[language.markdown.queries]
url = "https://github.com/phaazon/kak-tree-sitter"
pin = "d2d9761f309d6204a8f4480dc23f10558a165e29"
path = "runtime/queries/markdown"

# markdown.inline
[language."markdown.inline".grammar]
url = "https://github.com/MDeiml/tree-sitter-markdown"
pin = "231f3163cd27d48f91a4517cfdf72d167a9ef164"
path = "tree-sitter-markdown-inline/src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "markdown.inline.so"]
link_flags = ["-O3"]

[language."markdown.inline".queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/markdown.inline"

# matlab
# TODO

# mermaid
# TODO

# meson
# TODO

# msbuild
# TODO

# nasm
# TODO

# nickel
# TODO

# nim
# TODO

# nix
# TODO

# nu
# TODO

# ocaml
# TODO

# ocaml-interface
# TODO

# odin
# TODO

# opencl
# TODO

# openscad
# TODO

# org
# TODO

# pascal
# TODO

# passwd
# TODO

# pem
# TODO

# perl
# TODO

# php
# TODO

# po
# TODO

# ponylang
# TODO

# prisma
# TODO

# protobuf
# TODO

# prql
# TODO

# purescript
# TODO

# python
# TODO

# qml
# TODO

# r
# TODO

# racket
# TODO

# regex
# TODO

# rego
# TODO

# rescript
# TODO

# rmarkdown
# TODO

# robot
# TODO

# ron
# TODO

# rst
# TODO

# ruby
# TODO

# rust
[language.rust.grammar]
url = "https://github.com/tree-sitter/tree-sitter-rust"
pin = "0a70e15da977489d954c219af9b50b8a722630ee"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "rust.so"]
link_flags = ["-O3"]

[language.rust.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/rust"

# sage
# TODO

# scala
# TODO

# scheme
[language.scheme.grammar]
url = "https://github.com/6cdh/tree-sitter-scheme"
pin = "c0741320bfca6b7b5b7a13b5171275951e96a842"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "scheme.so"]
link_flags = ["-O3"]

[language.scheme.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/scheme"

# scss
# TODO

# slint
# TODO

# smithy
# TODO

# sml
# TODO

# solidity
# TODO

# sql
# TODO

# sshclientconfig
# TODO

# starlark
# TODO

# svelte
# TODO

# sway
# TODO

# swift
# TODO

# tablegen
# TODO

# task
# TODO

# tfvars
# TODO

# toml
[language.toml.grammar]
url = "https://github.com/ikatyang/tree-sitter-toml"
pin = "8bd2056818b21860e3d756b5a58c4f6e05fb744e"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "toml.so"]
link_flags = ["-O3"]

[language.toml.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/toml"

# tsq
# TODO

# tsx
# TODO

# twig
# TODO

# typescript
# TODO

# ungrammar
# TODO

# uxntal
# TODO

# v
# TODO

# vala
# TODO

# verilog
# TODO

# vhdl
# TODO

# vhs
# TODO

# vue
# TODO

# wast
# TODO

# wat
# TODO

# wgsl
# TODO

# wit
# TODO

# xit
# TODO

# xml
# TODO

# yaml
[language.yaml.grammar]
url = "https://github.com/ikatyang/tree-sitter-yaml"
pin = "0e36bed171768908f331ff7dff9d956bae016efb"
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.cc", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "yaml.so"]
link_flags = ["-O3", "-lstdc++"]

[language.yaml.queries]
url = "https://github.com/helix-editor/helix"
pin = "dbd248fdfa680373d94fbc10094a160aafa0f7a7"
path = "runtime/queries/yaml"

# yuck
# TODO

# zig
# TODO
